# Generated by Django 4.1.3 on 2022-11-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
