# Generated by Django 4.1.3 on 2022-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0006_alter_user_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default=2, max_length=191),
            preserve_default=False,
        ),
    ]
