# Generated by Django 4.1.3 on 2022-12-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0007_course_hours_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
