# Generated by Django 4.1.3 on 2022-12-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0011_alter_user_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='enrolled_students', to='school_system.course'),
        ),
    ]
